name: Invitation Only
author: DeltaWhy, Phoenix616
website: https://github.com/DeltaWhy/bukkit-invitation-only
main: com.github.deltawhy.invitationonly.InvitationOnly
version: 0.1.1
permissions:
  invitationonly.approve:
    description: Approve players for full membership.
    default: op
  invitationonly.unapprove:
    description: Revoke memberships.
    default: op
  invitationonly.quota:
    description: Change or refill other players' invite quotas.
    default: op
  invitationonly.invite:
    description: Invite new players (subject to probation).
    default: true
  invitationonly.uninvite:
    description: Revoke an invitation and kick the player - other players can still re-invite them.
    default: true
  invitationonly.invite.unlimited:
    description: Invite new players without quota.
    default: false
  invitationonly.vote.approve:
    description: Vote to approve a new player.
    default: true
  invitationonly.vote.ban:
    description: Vote to ban a new player (full members are safe).
    default: true
commands:
  invite:
    usage: /invite <username>
    description: Invite a new player (subject to probation).
    permission: invitationonly.invite
  uninvite:
    usage: /uninvite <username>
    description: Revoke an invitation and kick the player. Other players can still re-invite them.
    permission: invitationonly.uninvite
  invitequota:
    usage: /invitequota [username] [quota]
    description: View or update a player's invite quota.
    permission: invitationonly.quota
  approveinvite:
    usage: /approveinvite <username>
    description: Approve a probationary member or add a full member without probation.
    permission: invitationonly.approve
  unapprove:
    usage: /unapprove <username>
    description: Remove a player from the member list. Other players can re-invite them.
    permission: invitationonly.unapprove
  voteapprove:
    usage: /voteapprove <username>
    description: Vote to approve a probationary member.
    permission: invitationonly.vote.approve
  voteban:
    usage: /voteban <username>
    description: Vote to ban a probationary member.
    permission: invitationonly.vote.ban